# Generated by Django 5.0.6 on 2024-12-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.IntegerField(unique=True)),
                ('mots_de_passe', models.CharField(max_length=128)),
                ('annee_etude', models.CharField(max_length=14)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
