# Generated by Django 5.0.6 on 2024-12-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_box_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='creneau_horaire',
            field=models.DateTimeField(max_length=10),
        ),
    ]
