# Generated by Django 5.0.6 on 2025-01-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_reservation_creneau_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationServerice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
