# Generated by Django 5.0.6 on 2025-01-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reservationserverice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationServerice',
        ),
    ]
